[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@solidity-parser/=node_modules/prettier-plugin-solidity/node_modules/@solidity-parser/",
    "truffle/=node_modules/truffle/",
    "forge-std/=lib/forge-std/src/",
]
optimizer = true
optimizer_runs = 10000000
evm_version = "istanbul"
auto_detect_solc = true
# libraries = ["./contracts/utils/SignatureChecker.sol:SignatureChecker:0x9EC558745966cE2D5BBa7AaC081CAD53C9D6ab3F"]


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
xdai = "${GNOSIS_RPC_URL}"

[etherscan]
xdai = { key = "${GNOSISSCAN_API_KEY}", url = "https://api.gnosisscan.io/api?"}
sepolia = { key = "${ETHERSCAN_API_KEY}" }