[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "truffle/=node_modules/truffle/",
    "forge-std/=lib/forge-std/src/",
]
optimizer = true
optimizer_runs = 10000000
evm_version = "istanbul"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
xdai = "${GNOSIS_RPC_URL}"

[etherscan]
xdai = { key = "${GNOSISSCAN_API_KEY}", url = "https://api.gnosisscan.io/api?"}
sepolia = { key = "${ETHERSCAN_API_KEY}" }